### ISSUE TITLE
Contributors tab 

### ISSUE THREAD

**Issue by niharikaaa26** [nih326/PackFinder#13]

**Comment by niharikaaa26** [comment]
@all-contributors please add @nih326 , @sanjana1399,  @diya0603  for code

**Comment by niharikaaa26** [comment]
@all-contributors please add @diya0603 for code

**Comment by niharikaaa26** [comment]
@all-contributors please add @sanjana1399  for code

**Comment by niharikaaa26** [comment]
@all-contributors please add @nih326 for code

**Comment by diya0603** [comment]
I think issue can be closed

**Comment by diya0603** [comment]
@all-contributors please add @diya0603 for code

**Comment by diya0603** [comment]
@all-contributors 
please add @nih326 for code.
please add @sanjana1399 for code.

**Comment by diya0603** [comment]
@all-contributors
please add @nih326 for design.
please add @sanjana1399 for design.
please add @diya0603 fro design.

**Comment by diya0603** [comment]
@all-contributors
please add @diya0603 for design

**Comment by diya0603** [comment]
@all-contributors please add @sanjana1399 for design
